trigger: none

pool:
  vmImage: window-latest
  
stages:
- stage: A
  jobs:
  - job: A3
    steps:
    - script: echo "A1"
  
  - job: A4
    steps:
    - script: echo "A2"

- stage: B
  jobs:
  - job: B1
    steps:
    - script: echo "B1"

  - job: B2
    steps:
    - script: echo "B2"

